from typing import Optional, Union
from typing import Any, Literal, Optional, Dict,List
from datetime import datetime
from pydantic import BaseModel, Field
from typing_extensions import NotRequired, TypedDict
from enum import Enum
from langchain.schema import Document

class UserInput(BaseModel):
    """Basic user input for the agent."""

    message: str = Field(
        description="User input to the agent.",
    )
    thread_id: str | None = Field(
        description="Thread ID to look into the history",
        default=None,
    )
    org_region_id: Optional[str] | None =  Field(
        description="Organization region ID",
        default=None,
    )
    resource_type: Optional[List[str]] | None =  Field(
        description="Resource types of the user.",
        default=None,
    )


class ToolCall(TypedDict):
    """Represents a request to call a tool."""

    name: str
    """The name of the tool to be called."""
    args: dict[str, Any]
    """The arguments to the tool call."""
    id: str | None
    """An identifier associated with the tool call."""
    type: NotRequired[Literal["tool_call"]]


class ChatMessage(BaseModel):
    """Message in a chat."""

    type: Literal["human", "ai", "tool", "custom"] = Field(
        description="Role of the message.",
        examples=["human", "ai", "tool", "custom"],
    )
    content: str = Field(
        description="Content of the message.",
        examples=["Hello, world!"],
    )
    tool_calls: list[ToolCall] = Field(
        description="Tool calls in the message.",
        default=[],
    )
    tool_call_id: str | None = Field(
        description="Tool call that this message is responding to.",
        default=None,
        examples=["call_Jja7J89XsjrOLA5r!MEOW!SL"],
    )
    run_id: str | None = Field(
        description="Run ID of the message.",
        default=None,
        examples=["847c6285-8fc9-4560-a83f-4e6285809254"],
    )
    response_metadata: dict[str, Any] = Field(
        description="Response metadata. For example: response headers, logprobs, token counts.",
        default={},
    )
    custom_data: dict[str, Any] = Field(
        description="Custom message data.",
        default={},
    )
    documents: Optional[List[Document]] = Field(
        description="Documents of the message.",
        default=None,
    )

    def pretty_repr(self) -> str:
        """Get a pretty representation of the message."""
        base_title = self.type.title() + " Message"
        padded = " " + base_title + " "
        sep_len = (80 - len(padded)) // 2
        sep = "=" * sep_len
        second_sep = sep + "=" if len(padded) % 2 else sep
        title = f"{sep}{padded}{second_sep}"
        return f"{title}\n\n{self.content}"

    def pretty_print(self) -> None:
        print(self.pretty_repr())  # noqa: T201


class ChatHistoryInput(BaseModel):
    """Input for retrieving chat history."""

    thread_id: str = Field(
        description="Thread ID to look into the history",)

class ChatHistory(BaseModel):
    messages: list[ChatMessage]

class ChatResponse(BaseModel):
    message: ChatMessage = Field(
        description="The chat message generated by the agent.")
    
    data: Optional[Dict] = Field(
        default=None,
        description="Optional data associated with the chat response, e.g., onboarding data.")

# class DateRange(BaseModel):
#     start_date: Optional[datetime] = Field(description="""
#     Understand the start date from the user questions
#     1) if a single date or relative date (e.g., "last/previous 10 days", "last/previous month", "last/previous week", "yesterday") is mentioned,
#        return it in ISO 8601 format (YYYY-MM-DD).
#     2) If the user question mention or ask about some relevent date range but that date range is becoming the date range from previous year by calculating it with today's date
#        then set that start date accordingly with respect to previous year, month and day.
#     3) If the user question mentiones about something like : 'last 2 weeks/last 3 weeks/last 4 or 5 weeks', then calculatethe start_date by converting the number of weeks into days. As a week contains 7 days therefore 2 weeks should be 14 days before the today date. Then set the start_date accordingly. 
#     """, default=None)
#     end_date: Optional[datetime] = Field(description="""
#     Understand the end date from the user questions
#     - if a single date or relative date (e.g., "last 10 days", "last 1 month", "last week", "yesterday") is mentioned,
#       return it in ISO 8601 format (YYYY-MM-DD).""", default=None)

# class DateRange(BaseModel):
#     start_date: Optional[datetime] = None
#     end_date: Optional[datetime] = None


# class DateCount(BaseModel):
class DateRange(BaseModel):
    start_date: Optional[datetime] = Field(
        description="""
        Explicit or relative start date for a date range mentioned in the user question.
        Examples:
        - Single calendar dates: "January 6", "March 3", "from March 3 to April 16"
        - If the user mentions "today" or "today’s", set the start_date to today’s date.
        Note: Only fill this for actual date ranges or relative expressions that indicate a start date.
        Do NOT fill with numeric counts like 'last 10 days' here.
        """,
        default=None
    )
    end_date: Optional[datetime] = Field(
        description="""
        Explicit or relative end date for a date range mentioned in the user question.
        Examples:
        - Single calendar dates: "April 16"
        - If the user mentions "today" or "today’s", set the end_date to today’s date.
        Note: Only fill this for actual date ranges or relative expressions that indicate an end date.
        Do NOT fill with numeric counts like 'last 10 days' here.
        """,
        default=None
    )
    calendar_month: Optional[Union[str, List[str]]] = Field(
        description="""
        Month names explicitly mentioned in the user question.
        Examples: "January", "March", "December"
        Can be used with date ranges or counts, e.g., "last 20 days of January"
        """,
        default=None
    )
    days: Optional[int] = Field(
        description="""
        Number of day(s) mentioned as a duration or count in the user question.
        Examples: "last 10 days", "previous 5 days", "last 1 day", "past 20 days"
        Note: Use this for numeric counts, not absolute dates.
        
        - If user question mentions "recent" or "latest" set only `days` as 1.
        - Also set `days` as 1 when a day is mentioned without a number like: "yesterday/previous/past/last day(s)".
        - For phrases that are mentioning like: "last few days" or "past/previous few day(s)", set `days` as 5.
        """,
        default=0
    )
    weeks: Optional[int] = Field(
        description="""
        Number of week(s) mentioned as a duration or count in the user question.
        Examples: "last 2 weeks", "previous 4 weeks",  "last 1 week"
        Note: Use this for numeric counts, not absolute dates.

        - **Look for unnumbered durations in user question**: Set `weeks` as 1 when a week is mentioned like: "previous/past/last week(s)".
        - For phrases that are mentioning like: "last **few** weeks" or "past/previous few week(s)", set `weeks` as 2.
        """,
        default=0
    )
    months: Optional[int] = Field(
        description="""
        Number of month(s) mentioned as a duration or count in the user question.
        Examples: "last 3 months", "previous 1 month"
        Note: Use this for numeric counts, not absolute dates.

        - **Look for unnumbered durations in user question**: Set `months` as 1 when a month is mentioned like: "previous/past/last month(s)".
        - For phrases that are mentioning like: "last few months" or "past/previous **few** month(s)", set `months` as 3.
        """,
        default=0
    )
    years: Optional[int] = Field(
        description="""
        Number of year(s) or specific year mentioned in the user question.
        Examples: "last 2 years", "previous year", "2024", "last year"
        If no specific year is defined, set to 0.
        Note: Use this for numeric counts or explicitly mentioned years.
        
        - **Look for unnumbered durations in user question**: Set `years` as 1 when a year is mentioned like: "previous/past/last year".
        """,
        default=0
    )


